project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Health & Environmental Impacts of Warehousing in Ontario, CA"
  site-url: "https://dandaaa.github.io/Housing_site/" 
  repo-url: https://dandaaa.github.io/Housing_site/ 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Zhida Ma, 2024"

  sidebar:
    logo: images/image-1200x800-1.png
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/Dandaaa/Housing_site
        text: "MUSA 550 GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/zhida-ma-4a9b23165
        text: "Zhida Linkedin"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: Final-notebooks/Analysis Section.ipynb
        text: Analysis Sections
        contents:
          - href: Final-notebooks/1. AboutProject.ipynb 
            text: "1 About Project"
          - href: Final-notebooks/2. DataExploration.ipynb
            text: "2 Data Cleaning-Data Exploration"
          - href: Final-notebooks/2.1 EJIData.ipynb
            text: "2.1 Data Cleaning-EJI Data"
          - href: Final-notebooks/3. LoopingWarehouseMap.ipynb
            text: "3 Looping Warehouse Map"
          - href: Final-notebooks/4. Demographics.ipynb
            text: "4 Demographics"
          - href: Final-notebooks/5. Analysis.ipynb
            text: "5 Analysis"

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




